### ISSUE TITLE
Uploading multiple times produces multiple progress dialogs

### ISSUE THREAD

**Issue by GeoffPollard** [BlueQuartzSoftware/EasyBake#10]
Progress dialog closes, but when another upload starts a new progress dialog is created (and previously created ones are visible)
Don’t allow 2nd upload if one in progress

**Comment by rcharlesics** [comment]
Walked through replication with Chris but was unable to reproduce error. Possibly a Mac Issue

**Comment by rcharlesics** [comment]
Did create a possible fix. Please test

**Comment by joeykleingers** [comment]
Tested, and it appears to be fixed.
