### ISSUE TITLE
MetaData values that are "arrays" of values (LatticeConstants) are not being parsed into the UseTemplate Table.

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/EasyBake#16]
Guess is that the values are demarked by a set of "[]" and that may be interfering with the JSON parser?

**Comment by rcharlesics** [comment]
For this, we use json.dump and json.load. I believe that json is having a hard time recognizing the array, but unsure how to fix.

**Comment by rcharlesics** [comment]
added a string wrapper to the value column
