### ISSUE TITLE
HT Annotation & HT Units not editable within create template

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/EasyBake#17]
Load a datafile (ang).  Attempt to edit the HT Annotation & HT Units fields with click and/or double click and nothing happens.  True of "source" fields and custom fields.

**Comment by rcharlesics** [comment]
The solution now adds these keys into the dictionary and checks for them when edited. It is now saved over in the template BUT HT Annotation and HT Units are overwritted when extracting a new file on the use template. Do you want to use the template's units and annotation or?

**Comment by joeykleingers** [comment]
Appears to be fixed.
