### ISSUE TITLE
Checkbox to auto include parsed file on "Use Template" 

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/EasyBake#19]
Include a checkbox (default enabled) to auto included parsed datafile in the upload queue on "Use Template"

**Comment by rcharlesics** [comment]
Pushed a solution. Test if possible

**Comment by drowenhorst-nrl** [comment]
Looks good.  Can we make the default to be checked (default to autoload)?  This should be seen before any file is loaded.
