### ISSUE TITLE
Packages Save/Save as... 

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/EasyBake#20]
Save as ... does not work as expected.  

Suggestion: Currently "Save" acts as "Save As" in all cases (does not do an in place save, only offers to save a copy anyway).  This behavior is fine - I think an in place save is confusing in the this context.  Remove "Save" from the menu, and put all the code for "Save" under "Save As ..."

**Comment by rcharlesics** [comment]
pushed a solution. try now

**Comment by drowenhorst-nrl** [comment]
I would still recommend that "Save Package As ..." be the only option.  "Save" indicates a save in place.  "Save As ..." is indicating you are saving a new copy.

**Comment by rcharlesics** [comment]
will fix

**Comment by rcharlesics** [comment]
cool new solution. try now

**Comment by drowenhorst-nrl** [comment]
Looks great.
