### ISSUE TITLE
Canceling out of a Package "Save" throws an error

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/EasyBake#21]
Save a package, hit cancel at the save dialog.  

`Traceback (most recent call last):
  File "/Users/dave/PycharmProjects/MetaForge/EasyBake/mainwindowimpl.py", line 395, in savePackage
    with open(fileName[0]+"/"+self.currentTemplate, 'w') as outfile:
OSError: [Errno 30] Read-only file system: '/AM316.ez'`

**Comment by rcharlesics** [comment]
pushed up a solution try now
