### ISSUE TITLE
Switch UI to "Use Template" when opening a package

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/EasyBake#25]
Open the program, go directly to File -> Open Package -> Select Package locaton -> Open
Expected: UI should auto switch to the "Use Template" tab
Current: Stays on "Create Template" 

Take-flip and reverse for "Restore Template" -- if on the Use Package UI, after restoring Template, auto switch to "Create Template" tab.

**Comment by rcharlesics** [comment]
Pushed a solution. Try now

**Comment by drowenhorst-nrl** [comment]
Restoring Template does not switch to Create Template view.

**Comment by rcharlesics** [comment]
That one definitely went over my head. Try now
