### ISSUE TITLE
Use Template: Dragging files into the file list does not enable the button to select a HyperThought location.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/EasyBake#3]
After picking “Template File” and “File To Extract Metadata From”, dragging files into the file list does not enable the HyperThought Upload Folder Select button.

**Comment by rcharlesics** [comment]
the uploader folder is enabled/disabled on whether the file list is empty or not and now allows for drag and drop files to trigger this as well.
