### ISSUE TITLE
Create Template: Tri-state checkbox should appear in file tree for parents that have some children checked and some children unchecked.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/EasyBake#5]
<img width="249" alt="Screen Shot 2021-06-17 at 11 32 48 AM" src="https://user-images.githubusercontent.com/6197698/122428243-bfb3b380-cf5f-11eb-929e-e421e02643d8.png">

"011.ang" should have a tri-state checkbox because x-star, y-star, and z-star are checked but no other child is.

**Comment by rcharlesics** [comment]
Added a solution. Shall demo in meeting
