### ISSUE TITLE
Create Template: "HT Value" should be greyed out and read-only if "Use Source Value" is checked.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/EasyBake#7]
<img width="957" alt="Screen Shot 2021-06-17 at 11 48 37 AM" src="https://user-images.githubusercontent.com/6197698/122430879-f4c10580-cf61-11eb-802b-ac191eca943f.png">

"Use Source Value" is checked by default for each row when the table first populates, so each "HT Value" field should have --SOURCE-- as it's value and be greyed out and read-only.

**Comment by joeykleingers** [comment]
This is still not working quite right on the latest commit.

**Comment by joeykleingers** [comment]
"HT Value" cells need to be greyed out, not editable, and displaying --SOURCE-- any time that "Use Source Value" is checked.

**Comment by rcharlesics** [comment]
Fixed refreshing to be instant.

**Comment by joeykleingers** [comment]
Seems to be fixed.
