### ISSUE TITLE
Defined custom fields are not showing up on the Use Template side

### ISSUE THREAD

**Issue by GeoffPollard** [BlueQuartzSoftware/EasyBake#9]
When template is reloaded, HT Name showing, but not HT Value,

**Comment by imikejackson** [comment]
commit df15148 may fix this issue but needs testing.

@drowenhorst-nrl please test when you can

**Comment by imikejackson** [comment]
Testing a very simple case and uploading to ht.bluequartz.net seems to work. Checked the meta data on the HT server and the custom data is there. I think there may be issues with other editable rows in the template file.

**Comment by drowenhorst-nrl** [comment]
Yep - everything looks good for custom HTNames/HTValues now on the use template side. Will be opening up new report on HTAnnotations/HTUnits (custom or otherwise).

**Comment by rcharlesics** [comment]
pushed up a solution. Try now
